export const SPOTLIGHT_FLY_IN_DURATION = 3.0;
export const SPOTLIGHT_SHOWCASE_DURATION = 10.0;
export const SPOTLIGHT_RELEASE_DURATION = 3.0;

export const SPOTLIGHT_TOTAL_DURATION =
  SPOTLIGHT_FLY_IN_DURATION + SPOTLIGHT_SHOWCASE_DURATION + SPOTLIGHT_RELEASE_DURATION;
